sudo: required
language: ruby
services:
  - docker
install: true
script:
  - docker build -t procube/drbd9-rpm .
  - mkdir -p /tmp/RPMS/{x86_64,noarch}
  - sudo chown 111:111 -R /tmp/RPMS
  - docker run -it --rm --name drbd9-rpm -v /tmp/RPMS:/home/builder/rpmbuild/RPMS procube/drbd9-rpm
  - (cd /tmp;tar -czf - RPMS) > $TRAVIS_BUILD_DIR/drbd9-rpm.tar.gz
deploy:
  provider: releases
  api_key:
    secure: "ffL3K4gWkyqjiNna7Scubg/EL3HtuDrA8G9oVE4YBgw0tr7xuH2/k3or9wKIWYh0Rxz2skYFeWebjxEHmvCk86pAjbg1bC3TG+g2rfXyVzcnioKdaHhjS5FT0T0ieqOPDkKtHJHCuB6zwCrCDr8WnRkALTjd3F0kvHcddhw8fyjB+WEX28ZPcZjkeKBoV3OKZ3RpsRYPsODoM6aziEDwXAm/CWHAPvUVp7zITpCpdv7KE0B55uXTgbVhgmdrE7STkY3O3riaIeqLCgYL8RF2MK2eCT+sKLDTlMWbsoxYqw80TiRKqucVUYkF/PxFTeh0L6s4QQCPKfnKiMfYN+/j4rp1ohbCCM6E05hkoCcFuJGG3Tt871TzsghC266loj+LhQkiQd73Nn5T69uKCEY+D/oY7O9nQAu1QQHZoJo/tFE+WvO/ATB34W2wXT85G3l1BP+pF/JMcEBw8Wa906RFApPJqo/DemfiPyTYBw+tUeis8C01PCmO1q5kYPhiUYHxD7QZA7iDDK6NLv8LHOh609LTt64OrM5WUfoMj+DTPq/VlifhYIHYOsOf03O5U92T28HOHhGi6y8sWtk5bcHL7d0OwvWBVtXoqmF27ESX+OYXWGaDbmAqakgHlIk9pV+NzlP8CBAqXdC/qCCGTGo8iQ6E8GeNx4RNIErKTK3jfqs="
  file: drbd9-rpm.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: procube-open/drbd9-rpm
    tags: true
